# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5422f9fac7d7eba40761d274a25367ec8473a4a605b36d144952e204dbc64c055a966fe9e38099a4d171472de95bf37bc8205dfeb621da9343c61123565418b0

test:
  secret_key_base: 229d96a004319ab735b420089bc54a260facf08f7badf4ea701987b01359f7dc3944c78fae8ea0d84d8fd1d16160a8301abd873968238e433178fa35793dc61a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
